name: "NixOS Deploy"
on:
  pull_request:
  push:
jobs:
  nixos-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
      # Create with liberal rights, otherwise cache action will complain
      # about permission errors.
      sudo mkdir -p /nix/store
      sudo chmod -R 777 /nix
    # From https://github.com/cachix/install-nix-action/issues/56#issuecomment-1030697681
    - uses: actions/cache@v3
      with:
        path: |
          # See https://github.com/actions/cache/pull/726
          /nix/store/**
          # Missing something?
          /nix/var/nix/*/*
          /nix/var/nix/db/*
          /nix/var/nix/db/*/**
          !/nix/var/nix/daemon-socket/socket
          !/nix/var/nix/userpool/*
          !/nix/var/nix/gc.lock
          !/nix/var/nix/db/big-lock
          !/nix/var/nix/db/reserved
        key: ${{ runner.os }}-nix-store
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: 'mkdir -p $HOME/.ssh && echo -n "${NIXOS_SSH_KEY}" > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa'
      env:
        NIXOS_SSH_KEY: ${{ secrets.ssh_private_key }}
    - run: 'nix run .#deploy'
      env:
        NIXOS_SERVER_IP: ${{ secrets.nixos_server_ip  }}
