name: "NixOS Deploy"
on:
  pull_request:
  push:
jobs:
  nixos-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: 'mkdir -p $HOME/.ssh && echo "${NIXOS_SSH_KEY}" > $HOME/.ssh/id_rsa && sha256sum $HOME/.ssh/id_rsa'
      env:
        NIXOS_SSH_KEY: ${{ secrets.ssh_private_key }}
    - run: 'nix run .#deploy'
      env:
        NIXOS_SERVER_IP: ${{ secrets.nixos_server_ip  }}
