name: "NixOS Deploy"
on:
  pull_request:
  push:
jobs:
  nixos-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: 'echo "${NIXOS_SSH_KEY}" > ~/.id_rsa'
      env:
        NIXOS_SSH_KEY: ${{ secrets.nixos_ssh_key }}
    - run: 'nix run .#deploy'
